[package]
publish = false
name = "example-custom-ops"
version = "0.0.0"
edition = "2021"

[dependencies]
voicevox-ort = { path = "../../", features = [ "fetch-models" ] }
ndarray = "0.15"

[features]
load-dynamic = [ "voicevox-ort/load-dynamic" ]
cuda = [ "voicevox-ort/cuda" ]
